name: Main

on: pull_request

jobs:
  compile-and-lint:
    name: Compile and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: "package.json"
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: Transpile via TypeScript
        run: npm run compile
      - name: Prettier
        run: npm run prettier:check
      - name: ESlint
        run: npm run lint

  test:
    name: Integration testing
    needs: compile-and-lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: "package.json"
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund
      - name: Integration tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Integration testing
        run: npm test
        if: runner.os != 'Linux'
