name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  call-tests:
    name: Integration tests passed
    uses: ./.github/workflows/test.yaml

  release:
    name: Release
    needs: call-tests
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: write # to push git tags, update CHANGELOG.md and create GitHub Releases
      issues: write # to post comments on issues resolved in the new release
      pull-requests: write # to post comments on pull requests included in the new release
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: "package.json"

      - name: Install dependencies
        run: npm clean-install --prefer-offline --no-audit --no-fund

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Verify Marketplace Token
        run: npx vsce verify-pat $(jq --raw-output .publisher package.json)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Release
        id: semantic
        run: |
          npx --yes \
          --package semantic-release@25 \
          --package conventional-changelog-conventionalcommits \
          --package @semantic-release/changelog \
          --package semantic-release-vsce \
          --package @semantic-release/git \
          --package @semantic-release/github \
          semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
